[PHP] Upgrade GD to 2.3.3 (#2944)
## Motivation for the change, related issues

Upgrades GD version to 2.3.3. The EWWW Image Optimizer relies on GD
library features shipped with a more recent GD version than the one
bundled with PHP. See
https://github.com/nosilver4u/ewww-image-optimizer/pull/377

## Implementation details

PHP comes with a bundled GD version 2.1.0. Upgrading to 2.3.3 involves:

* Downloading and building 2.3.3 as a separate library (living in
`packages/php-wasm/compile/libgd`)
* Using it while compiling PHP 8.1+ via `--with-external-gd`
* Falling back to the bundled libgd==2.1.0 for PHP <= 8.0. These older
PHP releases don't seem to be compatible with newer GD and fail to build
due to multiple missing symbols, e.g. `/root/php-src/ext/gd/gd.c:3536:8:
error: use of undeclared identifier 'GD_FLIP_VERTICAL'`.

## Testing Instructions (or ideally a Blueprint)

CI – we have tests covering `gd` across all PHP versions.